const NOT_FRIENDS = 'NOT_FRIENDS'
const SENT_REQUEST = 'SENT_REQUEST'
const RECIEVED_REQUEST = 'RECIEVED_REQUEST'
const FRIENDS = 'FRIENDS'

module.exports = {
	NOT_FRIENDS,
	SENT_REQUEST,
    RECIEVED_REQUEST,
    FRIENDS
}